{
 "type": "1",
 "title": "Funcionamiento del ejemplo con errores",
 "description": "Muestra el funcionamiento de un servicios que detectan errores.",
 "printDescription": "Página para imprimir que muestra el funcionamiento de servicios que detectan errores.",
 "listado": [
  {
   "name": "m1cliente.html",
   "title": "Iniciamos al ejecutar código en el cliente",
   "description": "Muestra el código que se ejecuta en el cliente.",
   "esPruebaDeEscritorio": true
  },
  {
   "name": "m2servidor.html",
   "title": "Se invoca el servicio en el servidor",
   "description": "Muestra como se invoca el servicio en el servidor usando fetch.",
   "esPruebaDeEscritorio": true
  },
  {
   "name": "m3procesa.html",
   "title": "El servicio procesa la request, lanza una excepción y genera la response",
   "description": "Muestra como el servidor procesa la request, lanza una excepción y genera la response.",
   "esPruebaDeEscritorio": true
  },
  {
   "name": "m4devuelve.html",
   "title": "El servicio devuelve la response, que es recibida en el cliente",
   "description": "Fotografía de consolas de videojuegos.",
   "esPruebaDeEscritorio": true
  },
  {
   "name": "m5catch.html",
   "title": "Como hay error, se lanza una excepción que atrapa el catch",
   "description": "Como hay error, se lanza una excepción que atrapa el catch.",
   "esPruebaDeEscritorio": true
  },
  {
   "name": "m6muestraerror.html",
   "title": "Muestra la excepción en la consola y el mensaje de la excepción en un alert",
   "description": "Muestra la excepción en la consola y el mensaje de la excepción en un alert.",
   "esPruebaDeEscritorio": true
  },
  {
   "name": "m7termina.html",
   "title": "Al cerrar el alert, termina el evento",
   "description": "Al cerrar el alert, termina el evento.",
   "esPruebaDeEscritorio": true
  }
 ]
}